### API Requests for Server Testing

@server = http://localhost:8000/api/v1

@email = "hamis@lynrantic.co.tz"
@code = "SSH001"
@password = "SecureP@ss2025"

######################################################
### Authentication Requests
######################################################

### Login Request
# @name login
POST {{server}}/login
Content-Type: application/json
Accept: application/json

{
  "email": {{email}},
  "password": {{password}}
}

### Login Request
# @name login
POST {{server}}/login
Content-Type: application/json
Accept: application/json

{
  "code": {{code}},
  "password": {{password}}
}

### me
GET {{server}}/me
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

### Logout Request
POST {{server}}/logout
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

######################################################
### Register User Vendor Requests Public Routes
######################################################

### Register Vendor Request
# @name registerVendor
POST {{server}}/users/vendors/register
Content-Type: application/json
Accept: application/json

{
    "name": "Hamis Hamis",
    "email": "hamis@lynrantic.co.tz",
    "country_code": "255",
    "phone": "0758483019",
    "password": "SecureP@ss2025"
}

### Verify Email Request
# @name verifyEmail
POST {{server}}/verify-email?token=IIAkS5f73u4pCKjhXeWTvybUoRGlNQfkhmYpdLptSbKSfJfD4axHlY1eYf0RKmlY 
Content-Type: application/json
Accept: application/json


######################################################
### Vendor Registration Requests (Protected Routes)
######################################################

### @name listVendors
GET {{server}}/vendors
Authorization: Bearer {{login.response.body.$.data.token}}
Accept: application/json


### @name registerVendorProtected
POST {{server}}/vendors
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

{
    "country_id": 1,
    "tin": "123456789",
    "name": "The Aga Khan Fund for Economic Development SA (AKFED SA)",
    "email": "daressalaam@serenahotels.com",
    "phone": "222112416",
    "address": "Ohio Street P.O BOX 791 Dar es Salaam, Tanzania"
}

### @name showVendorProtected
GET {{server}}/vendors/07f2e905-7988-4d19-8930-67080ea4576a
Authorization: Bearer {{login.response.body.$.data.token}}
Accept: application/json

### @name updateVendorProtected
PUT {{server}}/vendors/07f2e905-7988-4d19-8930-67080ea4576a
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

{
    "country_id": 1,
    "tin": "123456789",
    "name": "The Aga Khan Fund for Economic Development SA (AKFED SA)",
    "email": "daressalaam@serenahotels.com",
    "phone": "222112416",
    "address": "Ohio Street P.O BOX 791 Dar es Salaam, Tanzania"
}
