### API Requests for Server Testing

@server = http://localhost:8000/api/v1

@email = "hamis@lynrantic.co.tz"
@code = "SSH001"
@password = "SecureP@ss2025"

######################################################
### Authentication Requests
######################################################

### Login Request
# @name login
POST {{server}}/login
Content-Type: application/json
Accept: application/json

{
  "email": {{email}},
  "password": {{password}}
}

### me
GET {{server}}/me
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

### Logout Request
POST {{server}}/logout
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

######################################################
### Register User Vendor Requests
######################################################

### Register Vendor Request
# @name registerVendor
POST {{server}}/users/vendors/register
Content-Type: application/json
Accept: application/json

{
    "name": "Hamis Hamis",
    "email": "hamis@lynrantic.co.tz",
    "country_code": "255",
    "phone": "0758483019",
    "password": "SecureP@ss2025"
}