### API Requests for Server Testing

@server = http://localhost:8000/api/v1

@code = "SSH001"
@password = "SSH001"

######################################################
### Authentication Requests
######################################################

### Login Request
# @name login
POST {{server}}/login
Content-Type: application/json
Accept: application/json

{
  "code": {{code}},
  "password": {{password}}
}

### me
GET {{server}}/me
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

### Logout Request
POST {{server}}/logout
Authorization: Bearer {{login.response.body.$.data.token}}
Content-Type: application/json
Accept: application/json

######################################################
### Vendor Registration Requests
######################################################

### Register Vendor Request
# @name registerVendor
POST {{server}}/vendors
Content-Type: application/json
Accept: application/json

{
    "name": "Vendor ABC",
    "email": "johndoe@example.com",
    "phone": "+1234567890",
    "password": "securepassword"
}